<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
	  <LangVersion>preview</LangVersion>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <OutputPath>..\1.4\Assemblies\</OutputPath>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\1.4\Assemblies\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.4.3901" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="NanameFloors_Unity\Library\**" />
    <Compile Remove="NanameFloors_Unity\Logs\**" />
    <Compile Remove="NanameFloors_Unity\obj\**" />
    <Compile Remove="NanameFloors_Unity\Packages\**" />
    <Compile Remove="NanameFloors_Unity\ProjectSettings\**" />
    <Compile Remove="NanameFloors_Unity\Temp\**" />
    <Compile Remove="NanameFloors_Unity\UserSettings\**" />
    <Compile Remove="NanameFloors_Unity\**" />
    <Compile Remove="NanameFloors_Unity1.5\**" />
    <Compile Remove="LegacyShaders\**" />
    <Compile Remove="packages\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="NanameFloors_Unity\Library\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\Logs\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\obj\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\Packages\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\ProjectSettings\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\Temp\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\UserSettings\**" />
    <EmbeddedResource Remove="NanameFloors_Unity\**" />
    <EmbeddedResource Remove="NanameFloors_Unity1.5\**" />
    <EmbeddedResource Remove="LegacyShaders\**" />
    <EmbeddedResource Remove="packages\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="NanameFloors_Unity\Library\**" />
    <None Remove="NanameFloors_Unity\Logs\**" />
    <None Remove="NanameFloors_Unity\obj\**" />
    <None Remove="NanameFloors_Unity\Packages\**" />
    <None Remove="NanameFloors_Unity\ProjectSettings\**" />
    <None Remove="NanameFloors_Unity\Temp\**" />
    <None Remove="NanameFloors_Unity\UserSettings\**" />
    <None Remove="NanameFloors_Unity\.vsconfig" />
    <None Remove="NanameFloors_Unity\Unity.gitignore" />
    <None Remove="NanameFloors.csproj.DotSettings" />
    <None Remove="NanameFloors_Unity\**" />
    <None Remove="NanameFloors_Unity1.5\**" />
    <None Remove="LegacyShaders\**" />
    <None Remove="packages\**" />
  </ItemGroup>
</Project>